{
 "title": "4 golden signals",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "description": "Status of running app on port 8080",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"app:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "http_requests_inflight_current / http_requests_inflight_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{pattern!=\"/metrics\", status=~\"4.+|5.+\"}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{pattern!=\"/metrics\"}[1m])) by (pattern)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{pattern!=\"/metrics\", status=~\"4.+|5.+\"}[1m])) / sum(increase(http_requests_total{pattern!=\"/metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.99 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum(rate(http_request_duration_seconds_historgram_bucket{pattern!=\"/metrics\"}[1m])) by (le, pattern)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.90 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.90,\n    sum(rate(http_request_duration_seconds_historgram_bucket{pattern!=\"/metrics\"}[1m])) by (le, pattern)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.5 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.5,\n    sum(rate(http_request_duration_seconds_historgram_bucket{pattern!=\"/metrics\"}[1m])) by (le, pattern)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}